language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
script:
  - flake8 .
  - coverage run --source='.' --omit=*/apps.py,manage.py manage.py test
after_success: coverage report
